services:
  backend:
    build: ./
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
        - ./src:/LMS/src
        - ./commands:/LMS/commands
        - ./pyproject.toml:/LMS/pyproject.toml
        - ./uv.lock:/LMS/uv.lock
        - ./.env:/LMS/.env
    command:
      - ./commands/run_app.sh
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '3G'
        reservations:
          cpus: '1.0'
          memory: '1G'
  postgres:
    image: postgres:16.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata: { }
  redisdata: { }
